name: Preparing to patch
runs:
  using: "composite"
  steps:
    - name: Set up jdk
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
      with:
        distribution: 'zulu'
        java-version: '21'
#    - name: Setup Cloudflare Warp
#      shell: bash
#      run: bash src/etc/cf_warp.sh
