name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        # Generate dynamic tag based on date and time (e.g. v2024.01.01-1200)
        TAG_NAME="v$(date +'%Y.%m.%d-%H%M')"
        echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
        
        echo "
        **This repository is not like any other repository. It does not create new releases; it only releases new files.**
        **Forget about scrolling whole release page find files. Just read [Readme.md](../main/README.md#microg-revanced) file and select apps you want download.**
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        [Revanced Extended anddea](https://github.com/anddea/revanced-patches/releases)
        [Revanced Extended for Android 6 & 7](https://github.com/kitadai31/revanced-patches-android6-7/releases)
        [Revanced Extended For Android 5:](https://github.com/d4n3436/revanced-patches-android5/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: "Revanced Build ${{ env.RELEASE_TAG }}"
        tag: ${{ env.RELEASE_TAG }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        makeLatest: true
