name: Releasing APK files
inputs:
  tag_name:
    description: "Tag name for the release"
    required: true
  release_notes:
    description: "Path to release notes file"
    required: false
  prerelease:
    description: "Mark as prerelease"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        # Use the provided release notes file directly if it exists
        if [[ -n "${{ inputs.release_notes }}" ]] && [[ -f "${{ inputs.release_notes }}" ]]; then
            cp "${{ inputs.release_notes }}" ${{ github.workspace }}-CHANGELOG.txt
        else
            # Fallback if no release notes are provided
            echo "Relase notes not found." > ${{ github.workspace }}-CHANGELOG.txt
        fi
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: "Revanced Build ${{ inputs.tag_name }}"
        tag: ${{ inputs.tag_name }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        makeLatest: ${{ inputs.prerelease == 'false' }}
        prerelease: ${{ inputs.prerelease }}
        allowUpdates: true
