name: Releasing APK files
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        [ReX](https://github.com/YT-Advanced/ReX-patches/releases)
        [ReX forked by anddea](https://github.com/anddea/revanced-patches/releases)
        [Revanced Extended for Android 6 & 7](https://github.com/kitadai31/revanced-patches-android6-7/releases)
        [Revanced Extended For Android 5:](https://github.com/d4n3436/revanced-patches-android5/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: Revanced & Revanced Extended
        tag: all
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: true
