name: Releasing APK files
inputs:
  tag_name:
    description: "Tag name for the release"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo "
        **Automated Release Build**
        **Built using the latest available patches and CLI tools as of the build time.**
        **Check [Readme.md](../main/README.md) for details and installation instructions.**
        **Change log** :point_down:
        [Revanced](https://github.com/revanced/revanced-patches/releases)
        [Revanced Extended](https://github.com/inotia00/revanced-patches/releases)
        [Revanced Extended Anddea](https://github.com/anddea/revanced-patches/releases)
        [Revanced Extended Arsclib](https://github.com/inotia00/revanced-patches-arsclib/releases)
        [Revanced LisoUseInAIKyrios](https://github.com/LisoUseInAIKyrios/revanced-patches/releases)
        [Twitter Piko](https://github.com/crimera/piko/releases)
        [Instafel](https://github.com/mamiiblt/instafel/releases)
        "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          ./release/*.apk
        name: "Revanced Build ${{ inputs.tag_name }}"
        tag: ${{ inputs.tag_name }}
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        makeLatest: true
        allowUpdates: true
