name: 2. Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Check new patch Morphe
        id: check-morphe
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh MorpheApp/morphe-patches latest youtube-morphe.apk
      - name: Check new patch Morphe Beta
        id: check-morphe-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh MorpheApp/morphe-patches prerelease youtube-beta-morphe.apk
      - name: Check new patch Revanced Extended forked by Anddea Stable Version
        id: check-rve-anddea-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches latest youtube-stable-anddea.apk
      - name: Check new patch Revanced Extended forked by Anddea Beta Version
        id: check-rve-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh anddea/revanced-patches prerelease youtube-beta-anddea.apk
      - name: Check new patch Twitter Piko Stable
        id: check-twitter-piko-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko latest twitter-stable-piko.apk
      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh crimera/piko prerelease twitter-beta-piko.apk
      - name: Check new patch DeReVanced
        id: check-derv
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh RookieEnough/De-ReVanced latest gg-photos-arm64-v8a-derevanced.apk
      - name: Check new patch Paresh
        id: check-paresh
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh Paresh-Maheshwari/paresh-patches latest telegram-web-version-paresh.apk
      - name: Check new patch hoo-dles
        id: check-hoo-dles
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh hoo-dles/morphe-patches latest protonvpn-hoo-dles.apk
      - name: Check new patch BiliRoamingM
        id: check-BiliRoamingM
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh sakarie9/BiliRoamingM latest bilibili-BiliRoamingM.apk
      - name: Check new patch Revanced Experiments
        id: check-Revanced-Experiments
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh Aunali321/ReVancedExperiments latest telegram-revanced-experiments.apk 
      - name: Re-run workflow if github connection not stable
        if: always() && steps.check-morphe.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: actions/github-script@v7
        with:
          script: |
            const maxRetries = ${{ env.max_retries }};
            let retryCount = ${{ env.retry_count }};
            if (retryCount < maxRetries) {
              retryCount += 1;
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "ci.yml",
                ref: context.ref,
                inputs: {
                  'retry_count': String(retryCount)
                }
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          retry_count: ${{ github.event.inputs.retry_count }}
          max_retries: 3
    outputs:
      check_morphe: ${{ steps.check-morphe.outputs.new_patch }}
      check_morphe_beta: ${{ steps.check-morphe-beta.outputs.new_patch }}
      check_rve_anddea_stable: ${{ steps.check-rve-anddea-stable.outputs.new_patch }}
      check_rve_anddea_beta: ${{ steps.check-rve-anddea-beta.outputs.new_patch }}
      check_rve_arsclib: ${{ steps.check-rve-arsclib.outputs.new_patch }}
      check_twitter_piko_stable: ${{ steps.check-twitter-piko-stable.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}
      check_paresh: ${{ steps.check-paresh.outputs.new_patch }}
      check_hoo_dles: ${{ steps.check-hoo-dles.outputs.new_patch }}
      check_BiliRoamingM: ${{ steps.check-BiliRoamingM.outputs.new_patch }}
      check_Revanced_Experiments: ${{ steps.check-Revanced-Experiments.outputs.new_patch }}

  Patch-Morphe:
    name: Patch Morphe
    needs: check
    if: ${{ needs.check.outputs.check_morphe == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Morphe"
  Patch-Morphe-Beta:
    name: Patch Morphe Beta
    needs: check
    if: ${{ needs.check.outputs.check_morphe_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Morphe Beta"
  Patch-RVE-anddea-stable:
    name: Patch RVX Anddea Stable
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-stable"
  Patch-RVE-anddea-beta:
    name: Patch RVX Anddea Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_anddea_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "RVE-anddea-beta"
  Patch-Revanced-Extended-Arsclib:
    name: Patch Revanced Extended Arsclib
    needs: check
    if: ${{ needs.check.outputs.check_rve_arsclib == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Arsclib"
  Patch-Twitter-Piko-Stable:
    name: Patch Twitter Piko Stable
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_stable == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Stable"
  Patch-Twitter-Piko-Beta:
    name: Patch Twitter Piko Beta
    needs: check
    if: ${{ needs.check.outputs.check_twitter_piko_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Twitter Piko Beta"
  Patch-DeRevanced:
    name: Patch DeRevanced Stable
    needs: check
    if: ${{ needs.check.outputs.check_derv == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "DeRevanced"
  Patch-Paresh:
    name: Patch Paresh
    needs: check
    if: ${{ needs.check.outputs.check_paresh == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Paresh"
  Patch-hoo-dles:
    name: Patch hoo-dles
    needs: check
    if: ${{ needs.check.outputs.check_hoo_dles == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "hoo-dles"
  Patch-BiliRoamingM:
    name: Patch BiliRoamingM
    needs: check
    if: ${{ needs.check.outputs.check_BiliRoamingM == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "BiliRoamingM"
  Patch-Revanced-Experiments:
    name: Patch Revanced Experiments
    needs: check
    if: ${{ needs.check.outputs.check_Revanced_Experiments == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Experiments"
